### ISSUE TITLE
Problem with formatting of scope resolution operator when refering to global namespace

### ISSUE THREAD

**Issue by ZimNovich** [NaturalDocs/NaturalDocs#11]
C++ does have the global namespace. It helps to differentiate some identifier from anything with the same name in any other namespace. To explicitly qualify a global identifier one can use the scope resolution operator with no name, i.e. `::SomeFunction(x);`.

I extensively use global namespaces in the library I am working on. The problem is when I try to compile a documentation for the library I get wrongly formatted scope resolution operator:

![propertyset_-_source_documentation_1](https://user-images.githubusercontent.com/34794580/34326941-673bd730-e8c9-11e7-8ef5-d5825a28cf03.png)

The C++ source code is:

```
// Constructor: PropertySet
// Get a single value from a pointer property. The wrapped OpenFX C-function is:
//
// Parameters:
//     property - is the string labelling the property
//     index    - is for multidimenstional properties and is dimension of the one we are setting
PropertySet(Host *h, ::OfxPropertySetHandle hdl);
```
@NaturalDocs

**Comment by NaturalDocs** [comment]
This has been fixed in version 2.0.2.
