### ISSUE TITLE
DB Document not linking properly

### ISSUE THREAD

**Issue by CyberSecDef** [NaturalDocs/NaturalDocs#18]
I'm trying to put a plain text database document together with the rest of the documentation for a project I'm building.  Everything parses, but the linking in the menu doesn't seem to work.

Details:
I have something along the lines of:
<SOME_PATH>\nwjs\nw applet files (no problem in here)
<SOME_PATH>\project\app\app files (js, html, css, etc....all parse fine)
<SOME_PATH>\project\app\database\databasefiles.db (all json objects, don't care about parsing these)
<SOME_PATH>\project\app\database\DATABASE.txt (this is where I'm putting the documentation)

The source documentation i have in here is:

Title: Configurations

Database: CSTSDB

Database Table: config
  config - This holds the configuration data for the the application

Column: _id

    --- Prototype ---
    _id VARCHAR(32) PRIMARY KEY NOT NULL
    -----------------

    This is the id for entries in the configuraiton collection
--------------------------------------------------------------------------------------------------
All this parses properly.  In the resulting HTML doc, left hand pane, I have:
Files, Classes, Database

If I go Files->database->config.txt....it shows up as expected

If, however, I go Database->CSTSDB...the page crashes and goes to the default index.

The link for Database->CSTSDB is showing up as:

DOCS/index.html#undefinedconfig

I'm guessing either the DATABASE.txt file needs to be named something differently, or maybe it has to match something inside?

Any help would be greatly appreciated!

**Comment by NaturalDocs** [comment]
Not an issue with the file name but something in the menu data generation.  This version has the fix which you can use until the next official release.

http://www.naturaldocs.org/temp/Natural_Docs_temp5.zip

**Comment by CyberSecDef** [comment]
Thank you so much.  And thanks for making such an awesome product!

-----Original Message-----
