### ISSUE TITLE
Block comments in Perl

### ISSUE THREAD

**Issue by docnux** [NaturalDocs/NaturalDocs#19]
Hello,

would it be possible to extend NaturalDocs to accept the "=pod" "=cut" pair as Perl block comment?
This would make editing and folding of documentation blocks in the IDE quite a bit easier.

**Comment by NaturalDocs** [comment]
You can use "=begin nd" and "=cut".  More details here:
http://www.naturaldocs.org/reference/comments/#perl_pod

**Comment by docnux** [comment]
... somehow I didn't notice that.
That's good enough for me, thanks!
