### ISSUE TITLE
Similar types do not group together.

### ISSUE THREAD

**Issue by Beakerboy** [NaturalDocs/NaturalDocs#29]
If I have a VBA class with a file structure like

````vba
Public Function foo (sbar as String)
...
End Function

Public Property Get Baz
...
End Property

Public Function Qix ()
...
End Function
````

The documentation does not group the two functions together. It lists
* Functions
    * foo
* Properties
    * Baz
* Functions
    * Qix

**Comment by NaturalDocs** [comment]
Correct.  Currently the summary is always shown in file order.  Being able to sort it different ways is a planned feature
