### ISSUE TITLE
zip file at naturaldocs.org uses backwards slashes

### ISSUE THREAD

**Issue by notestaff** [NaturalDocs/NaturalDocs#3]
The zip file at naturaldocs.org, meant for Unix systems, uses backwards slashes (\\) to separate directories.  This causes errors when unzipping on Unix.  @NaturalDocs

**Comment by NaturalDocs** [comment]
This has been fixed and all the zip files on naturaldocs.org have been reuploaded.

Backstory: A zip file should be a zip file should be a zip file, right?  And the zip files I uploaded worked fine in my Ubuntu VMs, but I got access to a Mac which wouldn't see the subfolders correctly, it would just treat them as part of the file name.  The original build process used a PowerShell command to generate the zip file.  Switching to zip on Ubuntu on the Windows Subsystem for Linux didn't help either.  Switching to using 7-Zip did even though it's a Windows application, so now the generated zip files open fine on the Mac.  I don't understand what behind the scenes difference there is in the zip files, but it works, so yay?
