### ISSUE TITLE
Application path on Ubuntu? (for Travis CI)

### ISSUE THREAD

**Issue by dotherightthing** [NaturalDocs/NaturalDocs#39]
I now have Natural Docs running on MacOS, but I'm having trouble identifying the correct path to get it running on Ubuntu (as used by Travis CI).

This is what I've tried:

1. `mono naturaldocs ./config`
    > Cannot open assembly 'naturaldocs': No such file or directory.
1. `mono naturaldocs/NaturalDocs.exe ./config`
    > Cannot open assembly 'naturaldocs/NaturalDocs.exe': No such file or directory.
1. `mono /usr/bin/naturaldocs/NaturalDocs ./config`
    > Cannot open assembly '/usr/bin/naturaldocs/NaturalDocs': Not a directory.
1. `mono > /usr/bin/naturaldocs ./config`
    > Cannot open assembly '> /usr/bin/naturaldocs': File does not contain a valid CIL image.
1. `mono > /usr/bin/naturaldocs/NaturalDocs.exe ./config`
    > Cannot open assembly '/usr/bin/naturaldocs/NaturalDocs.exe': Not a directory.
1. `mono > /usr/share/perl5/naturaldocs/NaturalDocs ./config`
    > Cannot open assembly '> /usr/share/perl5/naturaldocs/NaturalDocs': File does not contain a valid CIL image.

Obviously this list is not exhaustive, but each build takes several minutes.

This is how I install `mono` and `naturaldocs`:

```
before_install:
  # ...
  # Install Mono (NaturalDocs dependency)
  # https://www.mono-project.com/download/stable/#download-lin-ubuntu
  # Installed to > /usr/bin/naturaldocs
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https ca-certificates
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt install mono-complete
  # Install NaturalDocs
  # https://www.howtoinstall.co/en/ubuntu/trusty/naturaldocs
  # -y flag skips the installation confirmation prompt
  - sudo apt-get install -y naturaldocs
  # ...
  ```

I also ran a `dpkg` command, to try to ascertain where `apt-get install` installed the files to:

```
dpkg -L naturaldocs
```
> /.
> /usr
> /usr/bin
> /usr/bin/naturaldocs
> /usr/share
> /usr/share/perl5
> /usr/share/perl5/naturaldocs
> /usr/share/perl5/naturaldocs/Modules
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ClassHierarchy
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ClassHierarchy/File.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ClassHierarchy/Class.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Project.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Menu.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/File.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Menu
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Menu/Entry.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/BinaryFile.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Project
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Project/SourceFile.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Project/ImageFile.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Parser
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Parser/JavaDoc.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Parser/Native.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Parser/ParsedTopic.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ConfigFile.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ClassHierarchy.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Topics.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB/File.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB/ItemDefinition.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB/WatchedFileDefinitions.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB/Extension.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB/Item.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/CSharp.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/PLSQL.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Pascal.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Base.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Perl.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Ada.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Prototype
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Prototype/Parameter.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Advanced
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Advanced/ScopeChange.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Advanced/Scope.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Tcl.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Prototype.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/ActionScript.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Advanced.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Languages/Simple.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/File.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/Symbol.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/SymbolDefinition.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/IndexElement.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/ReferenceTarget.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable/Reference.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Constants.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/StatusMessage.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Parser.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Version.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ImageReferenceTable
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ImageReferenceTable/String.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ImageReferenceTable/Reference.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ImageReferenceTable.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Error.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Topics
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Topics/Type.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SourceDB.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolString.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Settings
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Settings/BuildTarget.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Settings.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/SymbolTable.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/NDMarkup.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/ReferenceString.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/LineReader.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder/FramedHTML.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder/Base.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder/HTML.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/Builder/HTMLBase.pm
> /usr/share/perl5/naturaldocs/Modules/NaturalDocs/DefineMembers.pm
> /usr/share/perl5/naturaldocs/Config
> /usr/share/perl5/naturaldocs/Config/Languages.txt
> /usr/share/perl5/naturaldocs/Config/Topics.txt
> /usr/share/perl5/naturaldocs/JavaScript
> /usr/share/perl5/naturaldocs/JavaScript/NaturalDocs.js
> /usr/share/perl5/naturaldocs/JavaScript/GooglePrettify.js
> /usr/share/perl5/naturaldocs/Styles
> /usr/share/perl5/naturaldocs/Styles/Small.css
> /usr/share/perl5/naturaldocs/Styles/Default.css
> /usr/share/perl5/naturaldocs/Styles/Roman.css
> /usr/share/perl5/naturaldocs/NaturalDocs
> /usr/share/doc
> /usr/share/doc/naturaldocs
> /usr/share/doc/naturaldocs/HTMLTestCases.pm.gz
> /usr/share/doc/naturaldocs/Languages.txt.gz
> /usr/share/doc/naturaldocs/NDMarkup.txt.gz
> /usr/share/doc/naturaldocs/Symbol Management.txt.gz
> /usr/share/doc/naturaldocs/changelog.Debian.gz
> /usr/share/doc/naturaldocs/images
> /usr/share/doc/naturaldocs/images/Logo.png
> /usr/share/doc/naturaldocs/copyright
> /usr/share/doc/naturaldocs/CSSGuide.txt.gz
> /usr/share/doc/naturaldocs/File Parsing.txt.gz
> /usr/share/man
> /usr/share/man/man1
> /usr/share/man/man1/naturaldocs.1.gz
> /usr/share/perl5/NaturalDocs

**Comment by NaturalDocs** [comment]
It looks like that package is the old Perl version of Natural Docs 1.x.  If you want to use Natural Docs 2.0 you'll need to [download it from the web site](https://naturaldocs.org/download/).  It should work on Ubuntu.

**Comment by NaturalDocs** [comment]
After that pointing Mono at NaturalDocs.exe should work.

**Comment by dotherightthing** [comment]
Thanks, I got it working in several different ways, which I've documented here: [Installing Natural Docs via the command line](https://gist.github.com/dotherightthing/9220394c260d73ef774e952c1f8b0ab0)
