### ISSUE TITLE
Fresh Install on Windows 10 but it doesn't work 

### ISSUE THREAD

**Issue by YeisonHunt** [NaturalDocs/NaturalDocs#40]
When I try to compile  a test, I run in my case:

NaturalDocs.exe E:\Proyectos\CSharpProjects\DocumentationTest\DocumentationTest Config
But nothing is generated, also, I changed the path to source folder, html ouput folder, title name in projects.txt but it doesn't work also.

Can you guys help me ?

**Comment by NaturalDocs** [comment]
Please post the Project.txt file you are using, the command line you are using, and the console output Natural Docs shows when it runs.

**Comment by NaturalDocs** [comment]
Closing for no response.  Feel free to reopen if you're still having trouble and want help.
