### ISSUE TITLE
Prototype of systemverilog module or class is not parsed properly

### ISSUE THREAD

**Issue by xdaanx** [NaturalDocs/NaturalDocs#43]
Is there a way (or workaround), how to fix issues below at my side? Am I doing something wrong?

In case of classes, the base class is not detected when I have parametrized class, e.g.:
```
// CLASS: A
class A #(type T = int) extends B #(.T(T));
```
or
```
// CLASS: C
class C #(type T = int) extends D;
```
In case of modules, the prototype is not shown properly if I use following syntax:
```
// MODULE: A
module A #(
  parameter  int          param_1 = 1,
  parameter  logic        param_2 = 0
) (
  input   logic           sig_1,
  input   int unsigned    sig_2,
  output  logic           sig_3
);
```
In case of modules (also functions and tasks), the prototype is not detected if I have a comment on a new line ( I usually use it, when there is a lot of signals).
e.g.
```
// MODULE: A
module A (
  input   logic           sig_1,
  // comment
  input   int unsigned    sig_2,
  output  logic           sig_3
);
```
I used following configuration:
```
Comment Type: Module
   Scope: Start
   Flags: Code
   Keywords:
      module, Modules
```
and 
```
   Module Prototype Ender: ;
   Class Prototype Ender: ;
```

Thanks a lot for the great tool, it creates a nice documentation.

**Comment by NaturalDocs** [comment]
The first two examples of parameterized classes now work in the latest development release.  You can download it here:

https://www.naturaldocs.org/download#Development

The third example works as well, though only the first set of parenthesis gets formatted line by line.  The second set just gets crammed on a single line afterwards.  This should change in a future release.

The fourth example, of having a full line comment appear within the prototype, isn't supported in any language and probably won't be in the near future.  Block comments are allowed if they appear on the same line as code but may throw off the formatting.  I don't know SV's syntax but in C++ this would work:

```
void MyFunction(
   /* in */ int x,
   /* out */ int* string
   )
```

but this wouldn't:

```
void MyFunction(
   int x,
   /* output */
   int* string
   )
```

**Comment by xdaanx** [comment]
Thank you for this update. I understand that it is not easy to support so many programming languages. I temporary fixed the rest of my current issues by overriding your methods and, so I am happy with current state and I am looking forward for future releases.

Regarding the full line comments in prototypes, they works in SystemVerilog. We usually use them as separator for group of signals (there might be hundreds of signals in top-level module port list).
