### ISSUE TITLE
Embed images into documentation

### ISSUE THREAD

**Issue by srupprecht1** [NaturalDocs/NaturalDocs#44]
Is it already possible to embed images or is there any solution in the foreseeable future? I couldn't find anything in the documentation.

**Comment by NaturalDocs** [comment]
It's not supported yet but it's the next non-language-specific feature I'm working towards.  I don't have a timetable though since it depends on some refactoring I'm doing.

**Comment by srupprecht1** [comment]
Latest version solves this. Thanks!
