### ISSUE TITLE
Link to www.naturaldocs.org from home.html should break out of frame

### ISSUE THREAD

**Issue by supbish** [NaturalDocs/NaturalDocs#48]
On the generated docs home page, there's a link to www.naturaldocs.org in the box in the middle of the page.

Firefox and Chrome can both prevent this link from opening because they don't want to serve iframes from a different domain as the containing document. Instead of a straight link, it should probably fire some JS to navigate top document to www.naturaldocs.org.

**Comment by NaturalDocs** [comment]
Good catch.  I added target="_blank" to it so not only does it work, it opens in a new tab.  Same with the link in the footer now.  This will appear in the next release.
