### ISSUE TITLE
Typing parameters for languages that do not have them

### ISSUE THREAD

**Issue by lkppo** [NaturalDocs/NaturalDocs#51]
Hello,

When the language does not allow defining the type of a function parameter, is there a way to use lists to manually make the type red?

Regards,

-- 
Stéphane Aulery

**Comment by NaturalDocs** [comment]
No, you'd have to include that in the description instead.

    Parameters:
    a - A string that does something.
    b - A <SomethingClass> that does something else.

**Comment by lkppo** [comment]
Ok, thanks. It's a matter of finding the right sentence then.
