### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by lkppo** [NaturalDocs/NaturalDocs#52]
Hello,

Keywords parameters and returns are missing from the Keywords list. For returns I understand but for parameters this is not the case as it triggers the automatic type annotation when using a named list.

Regards,

-- 
Stéphane Aulery

**Comment by NaturalDocs** [comment]
I'm not sure what you're referring to.  Could you post an example of what you're trying to do or would like to see?

**Comment by lkppo** [comment]
There are not in this list: 

https://www.naturaldocs.org/reference/keywords/

**Comment by NaturalDocs** [comment]
Right.  Keywords are only what starts the comments, like Function below.  Parameters and Returns are headings, which are part of the body.

    // Function: DoSomething
    //
    // Description
    //
    // Parameters:
    // a - The first one
    // b - The second one
    //
    // Returns:
    // Whether it was successful
    bool DoSomething (int a, int b)  { ... }

It does recognize some special headings like "Parameters" which are documented here instead:

https://www.naturaldocs.org/reference/formatting/#headings

**Comment by lkppo** [comment]
Ok. I see that Parameter (s) and Argument (s) are equally recognized. I would have thought that it was also a keyword of the code section in the same way that property is a sub-element of class but also has its keywords. A sort of sub-keyword.
