### ISSUE TITLE
Is the website built with ND itself?

### ISSUE THREAD

**Issue by lkppo** [NaturalDocs/NaturalDocs#54]
Hello,

Is the website built with ND itself?

I am looking in the repository but cannot find.

Regards,

-- 
Stéphane Aulery

**Comment by NaturalDocs** [comment]
The web site is built with a custom generator I wrote, but it's not open source so it's not in the repository.  It's probably too specialized to be used for any other sites so I don't plan on releasing it.

**Comment by lkppo** [comment]
Ok, I though it could be a sample of advanced customization. Thank you.
