### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by holmedor** [NaturalDocs/NaturalDocs#55]
I'm testing Image support in my project but I've done something wrong...

I've got this:

Generated on 2020-10-08 09:09:15

Crash Message:

   Can't add zero or negative numbers to an ID number set. (Resolver Thread 1)
   (System.ArgumentException)

Stack Trace:

   ----- Resolver Thread 1 -----
   en CodeClear.NaturalDocs.Engine.IDObjects.NumberSet.Add(Int32 number)
   en CodeClear.NaturalDocs.Engine.Output.HTML.UnprocessedChanges.AddClass(Int32 classID)
   en CodeClear.NaturalDocs.Engine.Output.HTML.Target.OnChangeImageLinkTarget(ImageLink imageLink, Int32 oldTargetFileID, EventAccessor eventAccessor)
   en CodeClear.NaturalDocs.Engine.CodeDB.Accessor.UpdateImageLinkTarget(ImageLink imageLink, Int32 oldTargetFileID)
   en CodeClear.NaturalDocs.Engine.Links.Resolver.ResolveImageLink(Int32 imageLinkID, Accessor accessor)
   en CodeClear.NaturalDocs.Engine.Links.Resolver.WorkOnResolvingLinks(CancelDelegate cancelled)
   en CodeClear.NaturalDocs.Engine.Thread.InternalStart()
   ----- Parent Thread -----
   en CodeClear.NaturalDocs.CLI.Application.Multithread(String threadName, CancellableTask task)
   en CodeClear.NaturalDocs.CLI.Application.BuildDocumentation(ErrorList errorList)
   en CodeClear.NaturalDocs.CLI.Application.Main(String[] commandLine)

Command Line:

   "D:\Natural Docs\"NaturalDocs.exe  D:\Natural Docs\ESP\NDconfig

Versions:

   Natural Docs 2.1 (Beta 1)
   Windows 10 Enterprise version 1909
   .NET 4.8
   SQLite 3.31.1

I'm attaching my Languages.txt, Project.txt, Comments.txt and TestingImageSupport.rb files (I've renamed the last one as .txt):
 
[Project.txt](https://github.com/NaturalDocs/NaturalDocs/files/5345935/Project.txt)

[Languages.txt](https://github.com/NaturalDocs/NaturalDocs/files/5345928/Languages.txt)

[Comments.txt](https://github.com/NaturalDocs/NaturalDocs/files/5346045/Comments.txt)

[TestingImageSupport.txt](https://github.com/NaturalDocs/NaturalDocs/files/5345964/TestingImageSupport.txt)

THANKS

**Comment by NaturalDocs** [comment]
I see exactly where I messed up and why it didn't show up in my testing.  Try this version:
https://www.naturaldocs.org/download/natural_docs/2.1/Natural_Docs_2.1_Beta_2.zip

**Comment by holmedor** [comment]
NOW, IT WORKS FINE!!!

;-)

THANKS!!!
