### ISSUE TITLE
Microsoft XML compatibility details link is forbidden

### ISSUE THREAD

**Issue by dswisher** [NaturalDocs/NaturalDocs#58]
The [Javadoc and XML](https://www.naturaldocs.org/reference/comments/#javadoc_and_xml) page says NaturalDocs does not have "perfect compatibility" with XML comments, and has a link for details: [Microsoft XML compatibility details](https://www.naturaldocs.org/documentation#File:Engine/Source/Comments/Parsers/XML.cs:CodeClear.NaturalDocs.Engine.Comments.Parsers.XML.Tag_Support). When I click on that link, I get a `403 Forbidden` response. (The same is true of the Javadoc link.)

I'm guessing it is attempting to link to a formatted version of the front-matter on the [XML.cs](https://github.com/NaturalDocs/NaturalDocs/blob/master/Engine/Source/Comments/Parsers/XML.cs) file?

**Comment by NaturalDocs** [comment]
Correct, it's the information in that file.  The web site links should work now as well.  For some reason sometimes when I upload the documentation the file permissions get set wrong, but it's fixed now.
