### ISSUE TITLE
Nested Parameters

### ISSUE THREAD

**Issue by Jayshua** [NaturalDocs/NaturalDocs#7]
Functions in JavaScript often take a configuration object as an argument (possibly with additional "normal" arguments). Is there a way to document the properties of this configuration object? I'd imagine that they ought to be nested in the output under the relevant parameter name.

Relatedly, is there a way to document the type of a function parameter in JavaScript?

**Comment by NaturalDocs** [comment]
The structure of the comments is freeform, so you can do something like this:

    /* Function: myJSFunction
     * Description
     * 
     * Parameters:
     * a - Description
     * b - Description
     * config - Description
     * 
     * Config Properties:
     * c1 - Description
     * c2 - Description
     * c3 - Description
     */
    function myJSFunction (a, b, config)
      { ... }

While you can't nest definition lists (i.e. put c1-c3 directly under config with extra indentation) you can add any number of headings you want and in any order.

As for parameter types, you'd have to document them with Natural Docs comments and then link them in the parameter comments somewhere, such as like this:

    /* Type: myJSType
     * Description
     */
    ...
    
    /* Class: myJSClass
     * Description
     */
    ...

    /* Function: myJSFunction
     * Description
     * 
     * Parameters:
     * a - A <myJSType> that...
     * b - A <myJSClass> object that...
     */
    function myJSFunction (a, b)
      { ... }

**Comment by Jayshua** [comment]
In C#, Natural Docs automatically determines the type and puts it under the parameter name.

![image](https://user-images.githubusercontent.com/1654103/30711427-481b91b4-9ece-11e7-9564-2dc1f53851c4.png)

I take it there's no way to do this explicitly in JavaScript then? Specifically, if I put &lt;string&gt; or &lt;number&gt; or &lt;array&gt; as the parameter type, it includes the angle brackets in the HTML output (I assume because I don't have types with those names defined anywere...)

If not, seems like that would be a good feature. I would have expected syntax something like

```
Parameters:
   a: int - First argument
   b: string - Second argument
```

Maybe with some type of optional and required marker for languages like JavaScript that allow optional arguments.

**Comment by NaturalDocs** [comment]
No, the feature doesn't work in JavaScript or any language that doesn't have declared parameter types.  It looks for them in the prototype, and since JavaScript only has the parameter name there's nothing to find.  I didn't make a manual way to do it.

My suggestion is instead to put them in the description and use the regular linking syntax when appropriate.  For documented types you can say "A <MyObject> that", but for built in types there's going to be nothing to link to so you would just say "A string that".  This is how I managed when I was writing in Perl, and how I still manage when writing JavaScript.

**Comment by Jayshua** [comment]
Would you be open to a pull request adding one or both of those features? I'm evaluating this tool for my company's documentation, and we're still trying to decide how badly we need those features.
