### ISSUE TITLE
Freeze on parsing

### ISSUE THREAD

**Issue by mmano** [NaturalDocs/NaturalDocs#74]
Hi,
I've a pretty huge existent C# source code base (documented with XML-comment and/or doxygen tags).
I've tried to investigate Natural Docs, but the tool freezes at parsing stage for a large number of my files.
It seems to correctly discovering and collecting my files. Parsing begins, but never finishes (from 10 to 96% ..), it freezes and consumes all the CPU. I've also tried with a subset of the files, but no chance.
Any warning or error don't bubble on the command line.
Did you implement a verbose switch, to find out where (and maybe why) the parsing may be locked ?
Thank you

**Comment by NaturalDocs** [comment]
Try this version: https://www.naturaldocs.org/download/temp/Natural_Docs_temp1.zip

With this one you can press S during the parsing stage to get a snapshot of what it's working on.  Run it until it hangs at 96%, press S, and see what files it's stuck on.  Hopefully from there we can start narrowing down what's causing the hang.

**Comment by mmano** [comment]
OK ... try to input
`<remarks>something:anything</remarks>`

**Comment by NaturalDocs** [comment]
Found the issue.  This one should fix it: https://www.naturaldocs.org/download/temp/Natural_Docs_temp2.zip

**Comment by mmano** [comment]
Yes, it fixes the issue, thanks. I'm going to wait for you to integrate those fixes into your trunk.
In the meantime, I continue to test Natural Docs because it looks very promising.

**Comment by NaturalDocs** [comment]
This fix has been included in [Natural Docs 2.3 Development Release 1](https://www.naturaldocs.org/download/#Development).

**Comment by NaturalDocs** [comment]
Natural Docs 2.3 has been released which includes this fix so I'm closing the issue.
