### ISSUE TITLE
Tab Naming and Hiding Options

### ISSUE THREAD

**Issue by paulhocker** [NaturalDocs/NaturalDocs#82]
Hello, I would like an option to change the Title of the Class tab to "Modules" or perhaps something else as the concept of "Class" is not correct for the documentation I am producing. Is that possible?

Secondly, add an option to suppress the files tab.

Would it be better to put these out on Github as issues or requests?

Lastly, I notice that there are pull requests on github. Do you actively review and accept those?

**Comment by NaturalDocs** [comment]
To rename classes, add this to [Comments.txt](https://www.naturaldocs.org/reference/comments.txt/) in your project folder. You'll have to run Natural Docs with -ro once afterwards to force the output to be rebuilt.

```
Alter Comment Type: Class
   Display Name: Module
   Plural Display Name: Modules
```

You can hide the files tab with CSS, though the underlying HTML files will still be generated. To do that [create a simple style](https://www.naturaldocs.org/reference/styles/#simple_styles) containing this line:

``` 
#MFileTab { display: none }
```

As for contributions, presently no. That could change in the future but not right now.

**Comment by paulhocker** [comment]
Thanks for that information. 

For the Tab Class, what I was talking about was the actual tab on the browser here

![image](https://user-images.githubusercontent.com/2214652/215168690-22a5fe1d-65a6-445d-a18b-a91d3eed908d.png)

I would very much like to change this to say Modules or something else.

Is that possible?

The trick for hiding the Files tab worked like a champ! Thanks for that!

**Comment by NaturalDocs** [comment]
Yes, editing Comments.txt should change it there.  If it doesn't it might be related to a bug that was fixed but hasn't made its way into a release yet.  Download the version linked to in the comments [here](https://www.reddit.com/r/NaturalDocs/comments/xd6olp/changing_display_name/).

**Comment by paulhocker** [comment]
That was it!

![image](https://user-images.githubusercontent.com/2214652/215185889-bf14fa19-3d06-416e-a932-4d6096c088be.png)

Is there a release planned soon? Is this version I tested pretty stable?

Thanks again.

**Comment by NaturalDocs** [comment]
It will still be some time until the next release.  That version should be pretty stable.

**Comment by NaturalDocs** [comment]
Natural Docs 2.3 was release which includes this fix, so I'm closing the issue.
