### ISSUE TITLE
New comment types does not get linked

### ISSUE THREAD

**Issue by eminakgun** [NaturalDocs/NaturalDocs#89]
Introducing new comment type and setting its scope to normal does not make it to be linked in other places,

```
Comment Type: SomeComment

   Scope: Normal
   Flags: Code

   Keywords:
      somecomment
```

Then using it,
```
interface some_if;

// somecomment: signal
int signal;

endinterface
```

And where it does not get linked is mentioning the variable in some place as `<some_if.signal>`.

But when I alter variable type, it works fine.

```
Alter Comment Type: Variable

   Keywords:
      somecomment
```

Natural Docs Version 2.2

**Comment by NaturalDocs** [comment]
That seems like you have it right.  Is the interface documented?  You would need a "// Interface: some_if" comment to set the scope in a way Natural Docs can see before signal will inherit it.  Otherwise it would be global and only linkable as <signal>, not <some_if.signal>.

**Comment by NaturalDocs** [comment]
It's been a couple of months without a response so I'm closing this.  Please reopen if you still want to work on this.
