### ISSUE TITLE
Function prototype with defaults does not parse

### ISSUE THREAD

**Issue by bentitmus** [NaturalDocs/NaturalDocs#9]
In SystemVerilog, a function with a default value is defined like this (declared similarly):
```
// Function: a
function void a(bit b = 1'b1);
endfunction
```
Natural Docs will not include the function signature in the generated documentation (presumably failing to parse it) when a default value is given. Signatures/prototypes for functions without default values are included as expected.

**Comment by samuelmswong** [comment]
I experienced that same issue. It seems that the apostrophe symbol is breaking the parser. 
SV commonly uses the apostrophe in default values so I haven't found a workaround for this

**Comment by NaturalDocs** [comment]
Are you using Natural Docs 2.3?  It was updated to have some support for SystemVerilog, including constants with apostrophes.  The example the original person posted works now:
```
// Function: a
function void a(bit b = 1'b1);
endfunction
```
If you have another example that doesn't work please post it.
