### ISSUE TITLE
Ignoring specific keywords?

### ISSUE THREAD

**Issue by tysenmoore-xse** [NaturalDocs/NaturalDocs#91]
I have read others asking about conditional documentation generation for public/private and everyone is using C# which has full support. For other languages, is it possible to add a "public", "private" keyword and depending on the loaded config or command line include or exclude those sections? Specifically I have classes in JS and since ES2015 they support private and public members. It would be great to simply document anything as "public" or "private". This could be useful for any basic language that is supported.

**Comment by NaturalDocs** [comment]
Yes.  You would build two sets of documentation with two separate project config folders.  In those folders you can [edit Comments.txt](https://www.naturaldocs.org/reference/comments.txt/) so keywords like "public function" are available in both but keywords like "private function" are only available in one.  That way private functions will only be included in one.

There's a partially implemented system for natively dealing with access levels but it's not usable yet.  In Natural Docs' config folder (where Natural Docs is installed, not your project config folder) edit Parser.txt to remove the things in the Access Level section.  That will prevent those keywords from being misinterpreted.

**Comment by tysenmoore-xse** [comment]
That worked great. Thanks so much for the fast response.

I was able to add the following to the `Comments.txt` for those interested. With these keywords the private information is added. With these missing the information is not added. 

```
Comment Type: Private Functions

   Keywords:
      private function
      private func


Comment Type: Private Properties

   Keywords:
      private property
      private prop
```
